name: "Clang Tidy Action"
on:
  pull_request:
    branches: [master]
    paths: ['**.c', '**.h', '**.am']
  push:
    paths: ['**.c', '**.h', '**.am']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEBIAN_FRONTEND: "noninteractive"

jobs:

  prepare-deps:
    name: Prepare dependencies
    uses: ./.github/workflows/prepare-deps.yml

  clang-tidy:
    name: clang-tidy
    runs-on: ubuntu-latest
    container: ubuntu:24.04
    needs: [prepare-deps]
    steps:
      - name: Cache ~/.cargo
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ~/.cargo/registry
          key: cargo-registry

      - name: Determine number of CPUs
        run: echo CPUS=$(nproc --all) >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          apt update
          apt -y install \
                autoconf \
                automake \
                build-essential \
                cargo \
                cbindgen \
                clang-19 \
                coccinelle \
                dpdk-dev \
                git \
                jq \
                libcap-ng-dev \
                libevent-dev \
                libevent-pthreads-2.1-7 \
                libhiredis-dev \
                libhyperscan-dev \
                libjansson-dev \
                libmagic-dev \
                libnet1-dev \
                libnetfilter-queue-dev \
                libnetfilter-queue1 \
                libnfnetlink-dev \
                libnfnetlink0 \
                libnuma-dev \
                libpcap-dev \
                libpcre2-dev \
                libpython3.12 \
                libtool \
                libyaml-dev \
                llvm-14-dev \
                make \
                parallel \
                python-is-python3 \
                python3-yaml \
                rustc \
                software-properties-common \
                zlib1g \
                zlib1g-dev
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: git config --global --add safe.directory /__w/suricata/suricata
      - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e
        with:
          name: prep
          path: prep
      - run: tar xf prep/suricata-update.tar.gz
      - run: tar xf prep/suricata-verify.tar.gz
      - run: ./autogen.sh
      - run: ./configure CC=clang
      - run: make compile-commands -j ${{ env.CPUS }}

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: ''  # disable clang-format checks. 
          tidy-checks: '' # Use .clang-tidy config file. 

      - name: Fail fast?!
        if: steps.linter.outputs.clang-tidy-checks-failed > 0
        run: exit 1
